service: meetings-microservice

frameworkVersion: '4.4.7'

provider:
  name: aws
  runtime: nodejs18.x  
  architecture: arm64
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 30
  vpc:
    securityGroupIds:
      - sg-123 
    subnetIds:
      - subnet-123

functions:
  api:
    handler: dist/lambda.handler
    timeout: 30         
    memorySize: 2048    
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-prune-plugin
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-plugin-optimize


custom:
  dotenv:
    path: .env.production
  prune:
    automatic: true
    include:
      - node_modules/.prisma/client
    exclude:
      - node_modules/**/*.md
      - node_modules/**/*.map
      - node_modules/**/test
      - node_modules/**/tests
      - node_modules/**/*.d.ts
      - node_modules/**/*.ts
      - node_modules/**/*.markdown
      - node_modules/**/docs
      - node_modules/**/*.snap
      - node_modules/**/example
      - node_modules/**/examples
      - node_modules/.cache
      - node_modules/@prisma/engines
      - node_modules/@types


package:
  include:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - '!node_modules/.cache/prisma/**'
    - 'node_modules/.prisma/**'
    - 'node_modules/@prisma/**'
    - 'dist/**'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
  excludeDevDependencies: true
  individually: true
  exclude:
    - .gitignore
    - package-lock.json
    - .git/**
    - .src/**
    - .vscode/**
    
