service: meetings-microservice

frameworkVersion: '4.4.7'

provider:
  name: aws
  runtime: nodejs18.x  
  architecture: arm64
  stage: production
  region: us-east-1
  memorySize: 2048
  logRetentionInDays: 1
  timeout: 30
  vpc:
    securityGroupIds:
      - sg-123  
    subnetIds:
      - subnet-123  

functions:
  api:
    handler: dist/lambda.handler
    timeout: 30         
    memorySize: 2048    
    events:
      - httpApi:
          method: any
          path: /{proxy+}

plugins:
  - serverless-jetpack
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  dotenv:
    path: .env.production

package:
  include:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-openssl-1.0.x*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - '!node_modules/.cache/prisma/**'
    - 'node_modules/.prisma/**'
    - 'node_modules/@prisma/**'
    - 'dist/**'
    - '!src/**'
    - '!test/**'
    - '!**/*.spec.ts'
    - 'node_modules/.prisma/client/libquery_engine-linux-arm64-*'
